### PR TITLE
Language support

### PR DESCRIPTION
**Pull request by wuke32767**
Now it will show other languages if your Celeste is not in English.
Uploaded Simplified Chinese translation.

### CODE REVIEW

**Comment by wuke32767** [comment]
I forgot to modify the version number

**Comment by RedFlames** [comment]
I see you've been working on this, sorry for not getting back to you on this yet.

What thread does this stuff even run in, do the async functions or UI parts have their own thread that you're sleeping? Surely it can't be the main thread being slept. 🤔 

Personally I was gonna use the same approach I used in CelesteNet for the repeat-delay on holding down the inputs like I implemented with this sub-class:
https://github.com/0x0ade/CelesteNet/blob/main/CelesteNet.Client/Components/CelesteNetChatComponent.cs#L106-L158

**Comment by wuke32767** [comment]
My apporach is too fancy, but they do the same for sure, so any one should be ok.
https://github.com/wuke32767/CollabLobbyUI/blob/main/Entities/NavMenu.cs#L135-L139 created a new thread. It waits .5f, and waits .05f repeatedly, before up/down key state is changed(pressed/released).

**Comment by RedFlames** [comment]
Oh right, it just repeats the action when it's being held. I still think maybe just using game time differences as delays is the better way to go here 😅 

Also forgot to mention, can you change the `COLLABLOBBYUI_Nav_Tips0` ... `COLLABLOBBYUI_Nav_Tips4` Dialog strings to follow the usual format of `MODOPTIONS_COLLABLOBBYUI_Nav_...` and then have more descriptive names? Same for all the local string variables where these get put to use. :)

And I saw that you made CollabUtils2 be a necessary dependency than an optional one which in hindsight definitely makes more sense than what I did, since without it the mod is pretty much useless anyways. I'll have to adjust the Reflection-stuff I did to work around the optional dependency that I made for myself, there's probably some stuff I can simply then.

**Comment by wuke32767** [comment]
`COLLABLOBBYUI_Nav_Tips0` might not be changed to `MODOPTIONS_COLLABLOBBYUI_Nav_` . It may be recognized as Mod Settings by Everest. 
Also forgot to mention, It's best not to remove `COLLABLOBBYUI_Nav_Tips0`, since it may be necessary for some special languages.
Other stuff up to you.

**Comment by RedFlames** [comment]
Hm, right, I kinda never used Dialog text outside of Mod Options I think, but yeah the name wouldn't make sense for the other UI bits.
I still don't like that they're just numbered `0` to `4` instead of having better names. In CelesteNet there's some Dialog strings that have placeholders like `((name))` and then a string replacement is done before the text gets shown. I think this could be done here too with a single UI hint string with placeholders for the keybinds. Then the format of the message could be entirely customized by translations as long as they have the placeholders in it.

Also, I've noticed you made this pull request from your `main` branch. Do you plan on making any other changes on there? It's not much of a problem here since you're the only contributor so far, but usually PRs are made from feature branches 😅 

I'll probably merge this in the next few days and then do the changes to the string as described.

**Comment by wuke32767** [comment]
You are right, I will not make any changes on main branch.
Any changes to the string is OK.

**Comment by wuke32767** [comment]
I have 1 more planned changes now. However, I won't have time for the next few days, so I may publish it after you merge this.

**Comment by RedFlames** [comment]
I hadn't even fully noticed "copied_CollabUtils2_CollabMapDataProcessor.cs" yet and that it's an exact copy of the class from CU2... I'm asking maddie480 if maybe that class can be marked `public` within CollabUtils2... then we could just access those static dictionaries there. I just tested it and that would work. 🤔 
But then if someone has a CU2 build where the processor class isn't public yet, the game crashes with a `System.FieldAccessException` so that wouldn't be good either. So I think I'll accept the copied MapDataProcessor and hopefully it can be removed again later, or a better solution to access those can be found.

Oh and did you not have any changes to your *.csproj that you would've committed?
image
Besides referencing CCU2 obviously, I also had to install System.ValueTuple via NuGet

**Comment by wuke32767** [comment]
By Reflection?
I don't think this is important. Players may not mind how much time it takes. My Celeste costs about 1 minute to load. Even if "copied_CollabUtils2_CollabMapDataProcessor.cs" costs 1 second, it makes no sense to me.
System.ValueTuple is used to compare multiple values, and only used once. I haven't noticed it is introduced in dotnet 4.7. Please change it as below.
In NavPointer.cs，166 line:
```
        public int Compare(NavPointer a, NavPointer b)
        {
            var v = b.hearted.CompareTo(a.hearted);
            if (v != 0)
            {
                return v;
            }
            v = a.strawberry_notcollected.CompareTo(b.strawberry_notcollected);
            if (v != 0)
            {
                return v;
            }
            v = (b.silvered || b.goldened).CompareTo(a.silvered || a.goldened);
            if (v != 0)
            {
                return v;
            }
            v = b.speeded.CompareTo(a.speeded);
            if (v != 0)
            {
                return v;
            }
            v = a.IconName.CompareTo(b.IconName);
            if (v != 0)
            {
                return v;
            }
            v = a.CleanName.CompareTo(b.CleanName);
            if (v != 0)
            {
                return v;
            }
            v = a.Map.CompareTo(b.Map);
           
            
            return v;
            
        }

```

**Comment by RedFlames** [comment]
Hm? We don't need to do anything with Reflection anymore, I'm taking out the bits where I accessed CCU2 stuff via Reflection later. You literally added a `using Celeste.Mod.CollabUtils2;`, added CollabUtils2 as an Assembly reference, and it's not an optional dependency in everest.yaml anymore. So there shouldn't be any Reflection going on... unless you meant to work around the fact that `CollabMapDataProcessor` isn't public in CollabUtils2?

Also I was not concerned about any runtime issues or load times, I just kind of dislike the fact that this has an exact copy of a class from CollabUtils2. But maybe it does need a `MapDataProcessor` and that implementation happens to be the one it needs. I will at the very least take the `copied_` off the filename at least. 😉 

Also that implementation of the Comparer is so long I'm almost tempted to keep the `ValueTuple` in :D

But I suppose there's not much to be done about that. I wish it was possible to chain the `CompareTo` calls, something like https://stackoverflow.com/a/26890988 might work, but idk if that's any better. 

---
I took some notes for myself on things I want to change, so I'll just merge this now and then do those changes.

I mostly wrote it for myself but might as well include it here,
__TODOs:__
 - `ButtonBinding vbTp ...` for string was wrong, only fixed it for releasing 1.0.2 but hadn't committed the changes...
 - get access to `CollabMapDataProcessor` via CCU2 instead? We'll see
 - placeholder string with `((...))` replacements for controls prompt text
 - fix Reflection-y CCU2 accesses
 - `AreaData AreaData` rename?...
 - replace `_NavEntrySelectedMutex` threaded Task stuff with delay helper class from CelesteNet
 - icon scale local var
 - remove `ValueTuple` again, maybe do comparer with nullable extension

**Edit:** I've done and pushed all of these except the Task/Button delay thing (still TODO for later) and I guess `AreaData AreaData` can stay, it looked odd to me at first that the member is named like the type, but eh, won't cause any issues, really.

**Pull request merged**
